# Permalinks
permalink:           pretty

# Setup
title:               DevBako
tagline:             ''
description:         'DevBako'
url:                 https://github.com/devbako/blog/
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              DevBako
  email:             devbako@ichino.se

# Custom vars
version:             1.0.0

# Gems
gems:                [jekyll-paginate, jekyll-gist]
