# Permalinks
permalink:           pretty

# Setup
title:               DevBako
tagline:             ''
description:         'DevBako'
url:                 http://devbako.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              DevBako
  email:             devbako@ichino.se

# Custom vars
version:             1.0.0

# Gems
gems:                [jekyll-paginate, jekyll-gist]
